### ISSUE TITLE
SP / PCでの画像表示サイズ制御をコンポーネント側で行うようにしたい

### ISSUE THREAD

**Issue by arie0703** [arie0703/portfolio-site#5]
## 概要

PCの画像表示はコンポーネントファイル, SPの画像表示はSCSSのメディアクエリでおこなっているが、コンポーネント側で制御するようにしたい

```ts
<Image src={item.image} width={selectedItem ? 30 : 80} height={selectedItem ? 30 : 80} alt={item.title} />
```

```scss
@media screen and (max-width: 768px) {
  .skills__flex {
    img {
      height: 50px;
    }
  }
}
```

## 参考情報
https://zenn.dev/nabeliwo/articles/89099b39223eca
